config/routes.rb
Rails.application.routes.draw do

  root "reviews#index"

  resources :save_posts

  delete "/reviews/:review_id/delete_picture_attachment/:index", to: 'reviews#delete_picture_attachment'

  delete "/posts/:post_id/delete_image_attachment/:index", to: 'posts#delete_image_attachment'

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :reviews do
    resources :review_comments
  end

  resources :memberships

  resources :groups do
    resources :posts do
      resources :post_comments
    end
  end

  devise_for :teachers, controllers: { registrations: 'teachers/registrations' }

  resources :teachers

  delete "/teachers/:id/delete_avatar", to: "teachers#delete_avatar"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "Teacher", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "Teacher", foreign_key: "receiver_id"
  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :receiver_id

  scope :between, -> (sender_id,receiver_id) do
    where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id)
  end

  def recipient(current_teacher)
    self.sender_id == current_teacher.id ? self.receiver : self.sender
  end

  def unread_message_count(current_teacher)
   self.messages.where("teacher_id != ? AND read = ?", current_teacher.id, false).count
 end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :teacher
  has_many :posts, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :teachers, :through => :memberships
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :teacher
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :teacher

  validates_presence_of :body, :conversation_id, :teacher_id

  private
    def message_time
      created_at.strftime("%d/%m/%y at %l:%M %p")
    end
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :image, styles: {
  thumb: '100x100>',
  square: '200x200#',
  medium: '300x300>'
}
# Validate the attached image is image/jpg, image/png, etc
validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :post_comments, dependent: :destroy
  has_many :save_posts, dependent: :destroy
  belongs_to :teacher
  belongs_to :group
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :teacher
  belongs_to :post
end

app/models/review.rb
class Review < ApplicationRecord
  has_attached_file :image, styles: {
  thumb: '100x100>',
  square: '200x200#',
  medium: '300x300>'
}
# Validate the attached image is image/jpg, image/png, etc
validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :review_comments, dependent: :destroy
  belongs_to :teacher
end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
  belongs_to :teacher
  belongs_to :review
end

app/models/save_post.rb
class SavePost < ApplicationRecord
  belongs_to :teacher
  belongs_to :post
end

app/models/teacher.rb
class Teacher < ApplicationRecord

  has_many :groups
  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :save_posts, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :groups, :through => :memberships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    if params[:q]
      @groups = Group.where('name LIKE ?', "%#{params[:q]}%")
    else
      @groups = Group.all
    end
  end

  def show
    @group = Group.find(params[:id])
    if teacher_signed_in?
      @membership = Membership.new
      @membership_cancel = Membership.find_by group_id: params[:id], teacher_id: current_teacher.id
    end
    if params[:q_posts]
      @posts = Post.where('title LIKE ?', "%#{params[:q_posts]}%")
    else
      @posts = @group.posts
    end

    if params[:q_members]
      @teachers = Teacher.where('username LIKE ?', "%#{params[:q_members]}%")
    else
      @teachers = @group.teachers
    end
  end

  def new
    @group = Group.new
  end

  def create
    group = Group.new(group_params)
    group.teacher_id = current_teacher.id

    if group.save
      flash[:notice] = 'group created!'
      redirect_to "/"
    else
      flash[:alert] = 'error. please try again'
      render "/groups/new"
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      flash[:notice] = 'group updated!'
      redirect_to "/groups/#{@group.id}"
    else
      flash[:alert] = 'error. please try again'
      render "/groups/#{@group.id}/edit"
    end
  end

  def destroy
    group = Group.find(params[:id])
    if group.destroy
      flash[:notice] = 'group destroyed'
      redirect_to groups_path
    else
      flash[:alert] = 'error. please try again'
      render "/groups/#{@group.id}/edit"
    end
  end

  def group_params
    params.require(:group).permit(:name, :description)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
    @group = Group.find(params[:group_id])
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @membership = Membership.find_by(group_id: params[:group_id], teacher_id: current_teacher.id)
    @save_post = SavePost.new
  end

  def new
    @group = Group.find(params[:group_id])
    @post = Post.new
    @membership = Membership.find_by(group_id: params[:group_id], teacher_id: current_teacher.id)
  end

  def create
    group = Group.find(params[:group_id])
    post = group.posts.build(post_params)
    post.group_id = group.id
    post.teacher_id = current_teacher.id

    if post.save!
      flash[:notice] = 'post created!'
      redirect_to "/"
    else
      flash[:alert] = 'error. please try again'
      redirect_to "/"
    end
  end

  def edit
    @group = Group.find(params[:group_id])
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])

    if post.update(post_params)
      flash[:notice] = 'post updated!'
      redirect_to "/groups/#{post.group_id}"
    else
      flash[:alert] = 'error. please try again'
      render "/groups/#{post.group_id}/posts/#{post.id}/edit"
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      flash[:notice] = 'post deleted!'
      redirect_to "/groups/#{post.group_id}"
    else
      flash[:alert] = 'error. please try again'
      render "/groups/#{post.group_id}/posts/#{post.id}/edit"
    end
  end

  def post_params
    params.require(:post).permit(:group_id, :title, :description, :price, :image, :request)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_page(active_page)
    @active == active_page ? "active" : ""
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/saves_helper.rb
module SavesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/groups/edit.html.erb
<div class="card text-center card-background">

<div class="inner-card-background">


  <% if teacher_signed_in? && @group.teacher_id == current_teacher.id %>
    <h2>edit group</h2>
    <%= form_for @group do |f| %>
      <div>Name</div>
      <div><%= f.text_field :name %></div>
      <div>Description</div>
      <div><%= f.text_area :description %></div>
      <div><%= f.submit "save changes"%></div>
      <%end%>

  <%= link_to 'Delete', group_path(@group), method: :delete, data:
  { confirm: 'Are you sure? This will delete all posts in the group.' } %>
  <% else %>
    <h2>Sorry! Only the creators of groups are allowed to edit them.</h2>
  <% end %>
</div>
</div>

app/views/groups/new.html.erb
<div class='card text-center card-background'>
<div class='inner-card-background'>
<% if teacher_signed_in? %>

  <%= form_for @group do |f| %>
      <%= f.label :name %>
      <div><%= f.text_field :name %></div>

      <%= f.label :description %>
      <div><%= f.text_area  :description %></div>
      <%= f.submit "create group"%>
      <%end%>
<% else %>
  <h2>Sorry! You must be signed in to create a group</h2>
<% end %>
</div>
</div>

app/views/groups/show.html.erb
<div id="groups-show-wrapper" >

  <div id='group-info'>
    <div class="card text-center card-background">

    <div class="inner-card-background">

  <h1><%= @group.name %></h1>

  <% if teacher_signed_in? && @group.teacher_id == current_teacher.id %>
    <%= link_to "Edit Group", "/groups/#{@group.id}/edit", class:"btn btn-primary" %>
    <%else%>
    <h4>Created by:
      <%= link_to "#{Teacher.find(@group.teacher_id).username}", "/teachers/#{Teacher.find(@group.teacher_id).id}", class:"" %>
    </h4>
  <%end%>

  <p><%= @group.description %></p>

  <% if teacher_signed_in? %>
  <% if @membership_cancel != nil%>
    <%= link_to 'leave group', membership_path(@membership_cancel), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
  <% else %>
    <%= form_for @membership do |f| %>
      <%= hidden_field_tag(:group_id, @group.id) %>
      <%= f.submit "join group", class: "btn btn-primary"%>
    <%end%>
  <%end%>
  <%end%>
</div>
</div>
  </div>
<div id='members-list'>
<%= form_tag("/groups/#{@group.id}", method: "get") do %>
  <%= label_tag(:q_members, "search members") %>
  <%= text_field_tag(:q_members) %>
  <%= submit_tag "search", class:"btn btn-primary", name: nil %>
<% end %>

<div class="">
  <h3>members(<%=@group.memberships.count%>):</h3>
  <% @teachers.each do |t| %>
    <%= link_to "#{t.username}", "/teachers/#{t.id}", class:"" %>
  <% end %>
</div>
</div>

<div id='post-list' class="text-center">
<%= form_tag("/groups/#{@group.id}", method: "get") do %>
  <%= label_tag(:q_posts, "search posts") %>
  <%= text_field_tag(:q_posts) %>
  <%= submit_tag "search", class: "btn btn-primary", name: nil %>
<% end %>

<% if teacher_signed_in? && @membership_cancel != nil%>
<div>
  <%= link_to "create post in #{@group.name}", "/groups/#{@group.id}/posts/new", class: "btn btn-primary" %>
</div>
<% else %>
 <div>join group to create and respond to posts!</div>
<%end%>

<h3>Posts:</h3>
<% @posts.reverse.take(5).each do |o| %>
 <div class='card'>
   <div><%= image_tag o.image.url(:medium) %></div>
  <%= link_to "#{o.title}", "/groups/#{@group.id}/posts/#{o.id}", class:"" %>
  <div><%= o.description%></div>
  <% if o.price == 0 && o.request == false%>
    <div class='free-post'>FREE</div>
  <% elsif o.request == true %>
      <div class='request-post'>REQUEST</div>
  <% else %>
    <div>$<%= o.price%></div>
  <% end %>
</div>
<% end %>
</div>

app/views/posts/edit.html.erb
<div class="card text-center card-background">

<div class="inner-card-background">
<h2>edit post</h2>

<%= image_tag @post.image.url(:square) %>

<% if @post.teacher_id == current_teacher.id %>

<%= form_for [@group, @post], multipart: true do |f| %>
  <%= f.label :title%>
  <div><%= f.text_field :title %></div>
  <div><%= f.label :request?%></div>
  <div>
  <%= f.label :yes%>
  <%= f.radio_button :request, true %>
  <%= f.label :no %>
  <%= f.radio_button :request, false %>
</div>
  <%= f.label :description%>
  <div><%= f.text_area :description %></div>
  <%= f.label :price%>
  <div><%= f.text_field :price, placeholder: 'put 0 if free or request' %></div>
  <div >
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <%= hidden_field_tag(:group_id, :group_id) %>
  <%= f.submit "save changes"%>
<%end%>

<%= link_to 'Delete', group_post_path(@post), method: :delete,
                         data: { confirm: 'Are you sure?' } %>
<% else %>

  <h2>Sorry, you have to be the owner of the post to edit.</h2>

<% end %>
</div>
</div>

app/views/posts/new.html.erb
<div class="card text-center card-background">

<div class="inner-card-background">

<% if @membership != nil %>

<%= form_for [@group, @post], multipart: true do |f| %>
  <%= f.label :title%>
  <div><%= f.text_field :title %></div>
  <div><%= f.label :request?%></div>
  <div>
  <%= f.label :yes%>
  <%= f.radio_button :request, true %>
  <%= f.label :no %>
  <%= f.radio_button :request, false %>
</div>
  <%= f.label :description%>
  <div><%= f.text_area :description %></div>
  <%= f.label :price%>
  <div><%= f.text_field :price, placeholder: 'put 0 if free or request' %></div>
  <div >
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <%= hidden_field_tag(:group_id, :group_id) %>
  <%= f.submit "create post"%>
<%end%>

<% else %>

<h2> Sorry! Must be a member of this group to create posts. </h2>

<% end %>
</div>
</div>

app/views/posts/show.html.erb
<div class="card text-center card-background">

<div class="inner-card-background">

<%= image_tag @post.image.url(:medium) %>

<div>
  <h3><%= @post.title %></h3>
  <% if @post.teacher_id == current_teacher.id %>
    <a href="/groups/<%= @post.group_id %>/posts/<%=@post.id%>/edit">edit</a>
  <% end %>
</div>

<%= form_for @save_post do |f| %>
  <%= hidden_field_tag(:post_id, @post.id) %>
  <%= f.submit "save post"%>
<%end%>

<div><%= @post.description%></div>

<% if @post.price == 0 && @post.request == false%>
  <div class='free-post'>FREE</div>
<% elsif @post.request == true %>
    <div class='request-post'>REQUEST</div>
<% else %>
  <div>$<%= @post.price%></div>
<% end %>

<div class="">Posted in: <%=Group.find(@post.group_id).name%></div>
<a href="/teachers/<%= @post.teacher_id %>">Posted by:<%= Teacher.find(@post.teacher_id).username %></a>
<hr>
<h4>Comments:</h4>
<hr>

  <% @post.post_comments.each do |c| %>
  <%= c.content %>
  <a href="/teachers/<%= c.teacher_id %>"><%= Teacher.find(c.teacher_id).username%></a>
    <% if teacher_signed_in? && c.teacher_id == current_teacher.id %>
      <%= link_to "edit", "/groups/#{@group.id}/posts/#{@post.id}/post_comments/#{c.id}/edit", class:"" %>
    <% end %>
    <hr>
  <%end%>


<% if @post.teacher_id == current_teacher.id %>
  <%= link_to "edit", "/groups/#{@post.group_id}/posts/#{@post.id}/edit", class:"" %>
<% end %>


    <div class=''>
      <%= form_for [@group, @post, @post_comment] do |f| %>
          comment:<%= f.text_field :content %>
          <%= f.submit id: ""  "post comment"%>
      <%end%>
    </div>

    <!-- <div class="comment-btns">JS comment button</div> -->

</div>
</div>