config/routes.rb
Rails.application.routes.draw do

  root "reviews#index"

  resources :save_posts

  delete "/reviews/:review_id/delete_picture_attachment/:index", to: 'reviews#delete_picture_attachment'

  delete "/posts/:post_id/delete_image_attachment/:index", to: 'posts#delete_image_attachment'

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :reviews do
    resources :review_comments
  end

  resources :memberships

  resources :groups do
    resources :posts do
      resources :post_comments
    end
  end

  devise_for :teachers, controllers: { registrations: 'teachers/registrations' }

  resources :teachers

  delete "/teachers/:id/delete_avatar", to: "teachers#delete_avatar"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "Teacher", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "Teacher", foreign_key: "receiver_id"
  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :receiver_id

  scope :between, -> (sender_id,receiver_id) do
    where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id)
  end

  def recipient(current_teacher)
    self.sender_id == current_teacher.id ? self.receiver : self.sender
  end

  def unread_message_count(current_teacher)
   self.messages.where("teacher_id != ? AND read = ?", current_teacher.id, false).count
 end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :teacher
  has_many :posts, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :teachers, :through => :memberships
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :teacher
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :teacher

  validates_presence_of :body, :conversation_id, :teacher_id

  private
    def message_time
      created_at.strftime("%d/%m/%y at %l:%M %p")
    end
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :image, styles: {
  thumb: '100x100>',
  square: '200x200#',
  medium: '300x300>'
}
# Validate the attached image is image/jpg, image/png, etc
validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :post_comments, dependent: :destroy
  has_many :save_posts, dependent: :destroy
  belongs_to :teacher
  belongs_to :group
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :teacher
  belongs_to :post
end

app/models/review.rb
class Review < ApplicationRecord
  has_attached_file :image, styles: {
  thumb: '100x100>',
  square: '200x200#',
  medium: '300x300>'
}
# Validate the attached image is image/jpg, image/png, etc
validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :review_comments, dependent: :destroy
  belongs_to :teacher
end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
  belongs_to :teacher
  belongs_to :review
end

app/models/save_post.rb
class SavePost < ApplicationRecord
  belongs_to :teacher
  belongs_to :post
end

app/models/teacher.rb
class Teacher < ApplicationRecord

  has_many :groups
  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :save_posts, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :groups, :through => :memberships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
    @group = Group.find(params[:group_id])
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @membership = Membership.find_by(group_id: params[:group_id], teacher_id: current_teacher.id)
    @save_post = SavePost.new
  end

  def new
    @group = Group.find(params[:group_id])
    @post = Post.new
    @membership = Membership.find_by(group_id: params[:group_id], teacher_id: current_teacher.id)
  end

  def create
    group = Group.find(params[:group_id])
    post = group.posts.build(post_params)
    post.group_id = group.id
    post.teacher_id = current_teacher.id

    if post.save!
      flash[:notice] = 'post created!'
      redirect_to "/"
    else
      flash[:alert] = 'error. please try again'
      redirect_to "/"
    end
  end

  def edit
    @group = Group.find(params[:group_id])
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])

    if post.update(post_params)
      flash[:notice] = 'post updated!'
      redirect_to "/groups/#{post.group_id}"
    else
      flash[:alert] = 'error. please try again'
      render "/groups/#{post.group_id}/posts/#{post.id}/edit"
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      flash[:notice] = 'post deleted!'
      redirect_to "/groups/#{post.group_id}"
    else
      flash[:alert] = 'error. please try again'
      render "/groups/#{post.group_id}/posts/#{post.id}/edit"
    end
  end

  def post_params
    params.require(:post).permit(:group_id, :title, :description, :price, :image, :request)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index

    if params[:q_group]
      @groups = Group.where('name LIKE ?', "%#{params[:q_group]}%")
    else
      @groups = Group.all
    end

    if params[:q_review]
      @reviews = Review.where('product LIKE ?', "%#{params[:q_review]}%")
    else
      @reviews = Review.all
    end
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.teacher_id = current_teacher.id

    if @review.save!
      flash[:notice] = 'review created!'
      redirect_to "/reviews"
    else
      flash[:alert] = 'error. please try again'
      render "/reviews/new"
    end
  end

  def show
    @review = Review.find(params[:id])
    @review_comment = ReviewComment.new
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    review = Review.find(params[:id])

    if review.update(review_params)
      flash[:notice] = 'review updated!'
      redirect_to "/reviews/#{review.id}/edit"
    else
      flash[:alert] = 'error. please try again'
      render "/reviews/#{review.id}/edit"
    end
  end

  def destroy
    review = Review.find(params[:id])

    if review.destroy
      flash[:notice] = 'review destroyed'
      redirect_to reviews_path
    else
      flash[:alert] = 'error. please try again'
      render "/reviews/#{review.id}/edit"
    end
  end

  def review_params
    params.require(:review).permit(:product, :content, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_page(active_page)
    @active == active_page ? "active" : ""
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/saves_helper.rb
module SavesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/reviews/edit.html.erb
<% if @review.teacher_id == current_teacher.id %>
<div class="card text-center card-background">

<div class="inner-card-background">

  <h2>edit review</h2>

  <%= image_tag @review.image.url(:medium) %>

  <%= form_for(@review, multipart: true) do |f| %>
    <%= f.label :product %>
    <div><%= f.text_field :product %></div>

    <%= f.label :content %>
    <div><%= f.text_area :content %></div>

    <div >
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>


    <%= f.submit "create review"%>
  <%end%>

  <%= link_to 'Delete', review_path(@review), method: :delete, data:
  { confirm: 'Are you sure?' } %>
</div>
</div>

<% else %>

<h2>Sorry! You must be the owner of the review to edit</h2>

<% end %>

app/views/reviews/index.html.erb
<div id='review-index-wrapper'>
<div>
  <h3>recent reviews</h3>
  <div class="">search reviews</div>
  <%= form_tag("/reviews", method: "get") do %>
    <%= text_field_tag(:q_review)%>
    <%= submit_tag "Search", class: "btn btn-primary", name: nil %>
  <% end %>

  <% @reviews.reverse.take(5).each do |r| %>
    <div class='card text-center'>
      <div><%= image_tag r.image.url(:medium) %></div>
      <%= link_to "#{r.product}", "/reviews/#{r.id}", class:"" %>
      Written by: <a href="/teachers/<%=r.teacher_id%>"><%= Teacher.find(r.teacher_id).username %></a>

    </div>
  <% end %>
</div>

<div class="">
  <% if teacher_signed_in? %>
  <div>
    <h3>your groups</h3>
      <% current_teacher.groups.each do |g|%>
        <div><%= link_to "#{g.name}", "/groups/#{g.id}", class:"" %></div>
      <%end%>
    <!-- <h3>groups you created:</h3>
      <% Group.where("teacher_id = #{current_teacher.id}").each do |g|%>
        <div><%= link_to "#{g.name}", "/groups/#{g.id}", class:"" %></div>
      <%end%> -->
      <hr>
  </div>
  <%end%>

  <h3>all groups</h3>
  <div class="">
    search groups
  </div>
  <%= form_tag("/reviews", method: "get") do %>
    <%= text_field_tag(:q_group) %>
    <%= submit_tag "Search", class: "btn btn-primary", name: nil %>
  <% end %>
  <% @groups.reverse.take(10).each do |g| %>
    <div><%= link_to "#{g.name}", "/groups/#{g.id}", class:"" %></div>
  <% end %>
</div>
</div>

app/views/reviews/new.html.erb
<div class="card text-center card-background">

<div class="inner-card-background">


  <%= form_for(@review, multipart: true) do |f| %>
    <%= f.label :product %>
    <div><%= f.text_field :product %></div>

    <%= f.label :content %>
    <div><%= f.text_area :content %></div>

    <div >
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>


    <%= f.submit "create review"%>
  <%end%>

</div>
</div>

app/views/reviews/show.html.erb
<div class="card text-center card-background">

<div class="inner-card-background">
<%= image_tag @review.image.url(:medium) %>
<div>Product: <%= @review.product %></div>
<div><%= @review.content %></div>
<div><a href="/teachers/<%= @review.teacher_id %>">-<%= Teacher.find(@review.teacher_id).username %></a></div>

<hr>
<h3 class="">comments:</h3>
<hr>
<% @review.review_comments.each do |c| %>
<%= c.content %>
<a href="/teachers/<%= c.teacher_id %>"><%= Teacher.find(c.teacher_id).username%></a>
  <% if teacher_signed_in? && c.teacher_id == current_teacher.id %>
    <%= link_to "edit", "/reviews/#{@review.id}/review_comments/#{c.id}/edit", class:"" %>
  <% end %>
  <hr>
<%end%>

<% if teacher_signed_in? %>
<!-- <div class="comment-btns">click to comment</div> -->
    <div class=''>
      <%= form_for [@review, @review_comment] do |f| %>
          comment:<%= f.text_field :content %>
          <%= f.submit id: ""  "post comment"%>
      <%end%>
    </div>
    <% if @review.teacher_id == current_teacher.id %>
      <%= link_to "Edit review", "/reviews/#{@review.id}/edit", class:"" %>
    <% end %>
<% end %>
</div>
</div>