config/routes.rb
Rails.application.routes.draw do

  root "reviews#index"

  resources :save_posts

  delete "/reviews/:review_id/delete_picture_attachment/:index", to: 'reviews#delete_picture_attachment'

  delete "/posts/:post_id/delete_image_attachment/:index", to: 'posts#delete_image_attachment'

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :reviews do
    resources :review_comments
  end

  resources :memberships

  resources :groups do
    resources :posts do
      resources :post_comments
    end
  end

  devise_for :teachers, controllers: { registrations: 'teachers/registrations' }

  resources :teachers

  delete "/teachers/:id/delete_avatar", to: "teachers#delete_avatar"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "Teacher", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "Teacher", foreign_key: "receiver_id"
  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :receiver_id

  scope :between, -> (sender_id,receiver_id) do
    where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id)
  end

  def recipient(current_teacher)
    self.sender_id == current_teacher.id ? self.receiver : self.sender
  end

  def unread_message_count(current_teacher)
   self.messages.where("teacher_id != ? AND read = ?", current_teacher.id, false).count
 end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :teacher
  has_many :posts, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :teachers, :through => :memberships
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :teacher
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :teacher

  validates_presence_of :body, :conversation_id, :teacher_id

  private
    def message_time
      created_at.strftime("%d/%m/%y at %l:%M %p")
    end
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :image, styles: {
  thumb: '100x100>',
  square: '200x200#',
  medium: '300x300>'
}
# Validate the attached image is image/jpg, image/png, etc
validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :post_comments, dependent: :destroy
  has_many :save_posts, dependent: :destroy
  belongs_to :teacher
  belongs_to :group
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :teacher
  belongs_to :post
end

app/models/review.rb
class Review < ApplicationRecord
  has_attached_file :image, styles: {
  thumb: '100x100>',
  square: '200x200#',
  medium: '300x300>'
}
# Validate the attached image is image/jpg, image/png, etc
validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :review_comments, dependent: :destroy
  belongs_to :teacher
end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
  belongs_to :teacher
  belongs_to :review
end

app/models/save_post.rb
class SavePost < ApplicationRecord
  belongs_to :teacher
  belongs_to :post
end

app/models/teacher.rb
class Teacher < ApplicationRecord

  has_many :groups
  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :save_posts, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :groups, :through => :memberships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
    @group = Group.find(params[:group_id])
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @membership = Membership.find_by(group_id: params[:group_id], teacher_id: current_teacher.id)
    @save_post = SavePost.new
  end

  def new
    @group = Group.find(params[:group_id])
    @post = Post.new
    @membership = Membership.find_by(group_id: params[:group_id], teacher_id: current_teacher.id)
  end

  def create
    group = Group.find(params[:group_id])
    post = group.posts.build(post_params)
    post.group_id = group.id
    post.teacher_id = current_teacher.id

    if post.save!
      flash[:notice] = 'post created!'
      redirect_to "/"
    else
      flash[:alert] = 'error. please try again'
      redirect_to "/"
    end
  end

  def edit
    @group = Group.find(params[:group_id])
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])

    if post.update(post_params)
      flash[:notice] = 'post updated!'
      redirect_to "/groups/#{post.group_id}"
    else
      flash[:alert] = 'error. please try again'
      render "/groups/#{post.group_id}/posts/#{post.id}/edit"
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      flash[:notice] = 'post deleted!'
      redirect_to "/groups/#{post.group_id}"
    else
      flash[:alert] = 'error. please try again'
      render "/groups/#{post.group_id}/posts/#{post.id}/edit"
    end
  end

  def post_params
    params.require(:post).permit(:group_id, :title, :description, :price, :image, :request)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_page(active_page)
    @active == active_page ? "active" : ""
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/saves_helper.rb
module SavesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Oswald|Work+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <%= favicon_link_tag asset_path('blackandwhite.png'), :rel => 'icon', :type =>  'image/png' %>
    <title>TeacherShare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-md navbar-dark sticky-top container-fluid" style="background-color: #3302cc;">
  <%= link_to 'TeacherShare', reviews_path, class:"navbar-brand" %>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarResponsive">
    <% if teacher_signed_in? %>
    <div class='navbar-item'>
      <%= link_to 'write review', new_review_path, class:"nav-link" %>
    </div>
    <div class='navbar-item'>
      <%= link_to 'create group', new_group_path, class:"nav-link" %>
    </div>

    <div class='navbar-item'>
      <%= link_to 'saved posts', save_posts_path, class:"nav-link" %>
    </div>

    <div class='navbar-item'>
      <%= link_to 'messages', conversations_path, class:"nav-link" %>
    </div>

    <div class='navbar-item'>
      <%= link_to 'profile', "/teachers/#{current_teacher.id}", class:"nav-link" %>
    </div>
    <div class='navbar-item'>
      <%= link_to 'logout', destroy_teacher_session_path, method: :delete, class:"nav-link" %>
    </div>
    <div class="navbar-item">
            <%= link_to "welcome, #{current_teacher.username}", edit_teacher_registration_path, class:"current-user nav-link" %>
    </div>

    <% else %>

      <div class='navbar-item logged-out-links'>
        <%= link_to 'login/signup', new_teacher_session_path, class:"nav-link float-right" %>
      </div>

    <% end %>
  </nav>
    </div>

    <% if current_page?(reviews_path) || current_page?('/') %>
    <div id="carouselwrapper" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselWrapper" data-slide-to="0" class="active"></li>
        <li data-target="#carouselWrapper" data-slide-to="1"></li>
        <li data-target="#carouselWrapper" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100" src="/assets/pencils.jpg" alt="First slide">
          <div class="carousel-caption d-none d-md-block">
            <h2 class='caption-h2'>share reviews</h2>
            <p class='caption-p'>Love a product? Let other teachers know!</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="/assets/abacus.jpg" alt="Second slide">
          <div class="carousel-caption d-none d-md-block">
            <h2 class='caption-h2'>share resources</h2>
            <p class='caption-p'>Get a donation you can't use? Share with teachers who need it!</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="/assets/books.jpg" alt="Third slide">
          <div class="carousel-caption d-none d-md-block">
            <h2 class='caption-h2'>share needs</h2>
            <p class='caption-p'>Need supplies for your class? Just ask!</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselwrapper" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselwrapper" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    </div>
    <% end %>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>